#ifndef ACEPLOT_H
#define ACEPLOT_H

#define ACELOG_STATUS (0x1000)

#define ACELOG_ERROR (ACELOG_STATUS | SIG_WORD | SIG_OFF0 | SIG_UNIT)

#define ACELOG_NAMES  {"LogE", ACELOG_ERROR}

#endif  // ACEPLOT_H
