#ifndef ACEPLOT_H
#define ACEPLOT_H

#define ACELOG_STATUS (SIG_PRIORITY_LOWEST | 0x00)

#define ACELOG_ERROR (ACELOG_STATUS | SIG_BYTE | SIG_OFF0 | SIG_UNIT)

#define ACELOG_NAMES  {"log/berr", ACELOG_ERROR}

#endif  // ACEPLOT_H
